import Head from "next/head";
import styles from "../../styles/Home.module.css";
import { useAuth } from "../../hooks/useAuth";
import { useRouter } from "next/router";

export default function Login() {
  const router = useRouter();
  const { requestLogin } = useAuth();
  const executeLogin = async () => {
    try {
      await requestLogin();
    } catch (error) {
      console.log("Loginをcatch!");
    }
    router.push("/");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App | Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button type="button" onClick={executeLogin}>
          login
        </button>
      </main>
    </div>
  );
}
