import Head from "next/head";
import { Me } from "../components/Me";
import styles from "../styles/Home.module.css";
import { useAuth } from "../hooks/useAuth";
import { HOOKS_STATE } from "../constants/hooks-state";
import { useRouter } from "next/router";

export default function Home() {
  const { getUser, logout } = useAuth();
  const { user } = getUser();
  const router = useRouter();
  if (user !== HOOKS_STATE.LOADING && user == null) router.push("/login");

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {user === HOOKS_STATE.LOADING || user == null ? (
          <>
            <p>Loading...</p>
          </>
        ) : (
          <>
            <Me name={user.name} email={user.email} />
            <button type="button" onClick={logout}>
              logout
            </button>
          </>
        )}
      </main>
    </div>
  );
}
